### ISSUE TITLE
nodejs 0.12 and above support?

### ISSUE THREAD

**Issue by dynnamitt** [substack/js-traverse#50]
I cannot use traverse in nodejs in 0.12 , 4.x and 5.x

 TypeError: Cannot read property 'node' of undefined

(sorry for bad stacktrace, but I cannot find the line in the traverse code.. just lots of my personal tests failing)

..will report more asap

**Comment by SEAPUNK** [comment]
I'm using this library for my applications (I'm using node 5.6), and it's working fine. What code is failing?

**Comment by NickHeiner** [comment]
I am also using this in Node v4.2.1, and it works fine. I'm guessing that your code has an error.

**Comment by blesson3** [comment]
Context is not set when using function short hand `(x) =>  { ... }` you must use `function` like so `function(x) { this... }`.

Hope this helps someone

**Comment by dynnamitt** [comment]
I can't reproduce anylonger
